import 'package:flutter/material.dart';

/// Design tokens copied 1:1 from the Web Admin's `resources/css/app.css`
/// `@theme` block (Tailwind v4 CSS-based config). Do not invent new colors
/// here — if a color is needed that doesn't exist below, it must come from
/// the Web Admin design system first (see TERESA_RIZAL_MOBILE_WEB_ALIGNMENT.md
/// Section 1). The Web Admin project itself is read-only; these values were
/// copied out of it, never generated by installing anything into it.
class AppColors {
  AppColors._();

  // Navy — sidebar / hero / dark surfaces.
  static const navy950 = Color(0xFF070F24);
  static const navy900 = Color(0xFF0B1730);
  static const navy800 = Color(0xFF12203F);
  static const navy700 = Color(0xFF1A2C52);
  static const navy600 = Color(0xFF24396B);

  // Brand — primary accent (blue).
  static const brand50 = Color(0xFFEEF4FF);
  static const brand100 = Color(0xFFDBE7FF);
  static const brand200 = Color(0xFFB8D0FF);
  static const brand300 = Color(0xFF8AB0FF);
  static const brand400 = Color(0xFF5687FF);
  static const brand500 = Color(0xFF2F62F5);
  static const brand600 = Color(0xFF1D47D6);
  static const brand700 = Color(0xFF1836A8);
  static const brand800 = Color(0xFF162C85);
  static const brand900 = Color(0xFF14276A);

  // Gold — Teresa, Rizal's own identity color (from the municipal seal), used
  // sparingly for accents, per the Web Admin's own app.css comment.
  static const gold50 = Color(0xFFFDF9E7);
  static const gold100 = Color(0xFFFBF0C2);
  static const gold200 = Color(0xFFF7E28A);
  static const gold300 = Color(0xFFF2D24F);
  static const gold400 = Color(0xFFECC02A);
  static const gold500 = Color(0xFFD9A91B);
  static const gold600 = Color(0xFFB48414);
  static const gold700 = Color(0xFF8A6412);

  // Slate — neutrals (Tailwind's default slate scale, as used throughout
  // the Web Admin for text/background/border on top of the custom tokens).
  static const slate50 = Color(0xFFF8FAFC);
  static const slate100 = Color(0xFFF1F5F9);
  static const slate200 = Color(0xFFE2E8F0);
  static const slate300 = Color(0xFFCBD5E1);
  static const slate400 = Color(0xFF94A3B8);
  static const slate500 = Color(0xFF64748B);
  static const slate600 = Color(0xFF475569);
  static const slate700 = Color(0xFF334155);
  static const slate800 = Color(0xFF1E293B);

  // Status system colors (Tailwind defaults) — must match badge.blade.php's
  // universal status system exactly. Each pair is [tint-bg, solid-dot/text].
  static const blue500 = Color(0xFF3B82F6);
  static const blue700 = Color(0xFF1D4ED8);
  static const blue50 = Color(0xFFEFF6FF);
  static const amber500 = Color(0xFFF59E0B);
  static const amber700 = Color(0xFFB45309);
  static const amber50 = Color(0xFFFFFBEB);
  static const indigo500 = Color(0xFF6366F1);
  static const indigo700 = Color(0xFF4338CA);
  static const indigo50 = Color(0xFFEEF2FF);
  static const purple500 = Color(0xFFA855F7);
  static const purple700 = Color(0xFF7E22CE);
  static const purple50 = Color(0xFFFAF5FF);
  // Tailwind sky-*, which is what the Web Admin's `bg-sky-50 text-sky-700
  // bg-sky-500` classes on the `Resubmitted` badge resolve to. Not a new
  // colour invented here: every status hex in this file is the Tailwind
  // default the shared badge component already uses (orange-500 #F97316,
  // emerald-50 #ECFDF5, purple-50 #FAF5FF ... all verified matching).
  static const sky500 = Color(0xFF0EA5E9);
  static const sky700 = Color(0xFF0369A1);
  static const sky50 = Color(0xFFF0F9FF);
  static const orange500 = Color(0xFFF97316);
  static const orange700 = Color(0xFFC2410C);
  static const orange50 = Color(0xFFFFF7ED);
  static const emerald500 = Color(0xFF10B981);
  static const emerald700 = Color(0xFF047857);
  static const emerald50 = Color(0xFFECFDF5);
  static const rose500 = Color(0xFFF43F5E);
  static const rose600 = Color(0xFFE11D48);
  static const rose700 = Color(0xFFBE123C);
  static const rose50 = Color(0xFFFFF1F2);
  static const teal500 = Color(0xFF14B8A6);
  static const teal700 = Color(0xFF0F766E);
  static const teal50 = Color(0xFFF0FDFA);
  static const cyan500 = Color(0xFF06B6D4);
  static const cyan700 = Color(0xFF0E7490);
  static const cyan50 = Color(0xFFECFEFF);
  static const green500 = Color(0xFF22C55E);
  static const green700 = Color(0xFF15803D);
  static const green50 = Color(0xFFF0FDF4);

  // Semantic aliases used across the mobile app.
  static const success = emerald500;
  static const warning = amber500;
  static const danger = rose600;
  static const info = brand500;

  static const background = slate50;
  static const surface = Colors.white;
  static const border = slate100;
  static const textPrimary = navy900;
  static const textBody = slate800;
  static const textMuted = slate400;
}
